# Generated by Django 3.0.2 on 2020-01-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileShare_app', '0002_auto_20200106_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myfile',
            old_name='name',
            new_name='a_file',
        ),
        migrations.RemoveField(
            model_name='myfile',
            name='can_see',
        ),
        migrations.AddField(
            model_name='myfile',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
