# Generated by Django 3.0.2 on 2020-01-07 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileShare_app', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myfile',
            name='a_file',
            field=models.FileField(upload_to='files'),
        ),
    ]
