# Generated by Django 3.0.2 on 2020-01-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileShare_app', '0007_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
