# Generated by Django 3.0.2 on 2020-01-14 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileShare_app', '0008_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfile',
            name='can_see',
            field=models.ManyToManyField(related_name='can_see', to=settings.AUTH_USER_MODEL),
        ),
    ]
