# Generated by Django 3.0.2 on 2020-01-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileShare_app', '0010_auto_20200115_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myfile',
            name='publish',
        ),
        migrations.AddField(
            model_name='myfile',
            name='publish_comment',
            field=models.BooleanField(default=True),
        ),
    ]
