# Generated by Django 3.0.2 on 2020-01-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileShare_app', '0011_auto_20200115_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='publish_comment',
            field=models.BooleanField(default=False),
        ),
    ]
