# Generated by Django 2.2.9 on 2020-01-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileShare_app', '0012_auto_20200115_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
