version: '3.1'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: prosgres_user
      POSTGRES_DB: fileDB
    
  mongo:
    image: mongo
    restart: always
    ports: 
        - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  redis:
    container_name: redis
    image: redis:4.0.11
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    restart: always

  pgAdmin:
    restart: always
    image: dpage/pgadmin4
    ports:
        - "5050:80"
    environment:
        PGADMIN_DEFAULT_EMAIL: 1234@admin.com
        PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
        - pgadmin:/var/lib/pgadmin
volumes:
  postgres:
  pgadmin: